### ISSUE TITLE
Migrating microstates into thefrontside organization

### ISSUE THREAD

**Issue by minkimcello** [microstates/microstates#1]
## Motivation
We want to combine the repositories of @microstates into a monorepo and transfer ownership to @thefrontside.

## Approach
- [ ] Decide which packages we want to add to the monorepo:
  - [x] [microstates.js](https://github.com/microstates/microstates.js)
  - [ ] [lab](https://github.com/microstates/lab)
  - [ ] [todomvc](https://github.com/microstates/todomvc)
  - [ ] [react](https://github.com/microstates/react)
  - [ ] [ember](https://github.com/microstates/ember)
  - [ ] [effects](https://github.com/microstates/effects)
  - [ ] [lens](https://github.com/microstates/lens)
  - [ ] [union](https://github.com/microstates/union)
  - [ ] [trafficlight](https://github.com/microstates/trafficlight)
  - [ ] [microstates.io](https://github.com/microstates/microstates.io)
  - [ ] [shopping-cart-example](https://github.com/microstates/shopping-cart-example)
- [ ] Clean up pull requests and issues on microstates org and archive all the repositories
- [ ] Transfer ownership of microstates monorepo to thefrontside org

**Comment by cowboyd** [comment]
Let's be lazy about which packages need to be in the monorepo so that it doesn't block. What if we get the monorepo set up first with just the microstates code, and migrated over to the frontside org, and then decide which packages we want to bring over.
